### ISSUE TITLE
Build mosaic from list of images instead list of files 

### ISSUE THREAD

**Issue by arruda-gustavo** [rafribeiro/forensicface#5]
The function build mosaic only accepts a list of paths to images and sometimes The images are already loaded.

**Comment by rafribeiro** [comment]
Added on commit https://github.com/rafribeiro/forensicface/commit/7161a0fb710de47388a474215c79ee633ef8e844.
Passing a list of arrays as an argument to build_mosaic is now accepted, but it prints a warning to the user to alert the BGR images should be used.
